<a href="https://colab.research.google.com/github/sush0677/pytorch_coding/blob/main/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#pytorch fundamentals
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.3.1+cu121


In [2]:
#intro to tensors
scalar = torch.tensor(7)
scalar #lowercase naming

tensor(7)

In [3]:
scalar.ndim #dimension
scalar.item()

7

In [4]:
vector = torch.tensor([7,7])
vector #1 dimension #lowercase naming

tensor([7, 7])

In [5]:
vector.shape

torch.Size([2])

In [6]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX #2 dimensions #uppercase

tensor([[ 7,  8],
        [ 9, 10]])

In [7]:
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR #it dimension is {1,3,3} #uppercase

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [8]:
#random tensor
random_tensor = torch.rand(3,4)
random_img_size_tensor = torch.rand(size=(224,224,3))
random_img_size_tensor.shape, random_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [9]:
#zeros and ones tensor
zeros = torch.zeros(size=(3,4))  # tensor datatype = torch.float
ones = torch.ones(size=(3,4))
zeros, ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [10]:
#creating a range of tensor
range= torch.arange(start=0,end=1000,step=77)
range

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [11]:
#creating tensors like
ten_zeros = torch.zeros_like(input=range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
float32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,
                              device=None,
                              requires_grad=False)
float32_tensor.dtype

torch.float32

In [13]:
# Manipulating tensors
tensor = torch.tensor([1,2,3])
tensor + 10
tensor * 10
tensor - 1

tensor([0, 1, 2])

In [14]:
torch.mul(tensor,10) #pytorch in built function(element-wise multiplication)

tensor([10, 20, 30])

In [15]:
#Matrix multiplication
%%time
torch.matmul(tensor,tensor) # matrix mul  symbol is @ The matrix inner dimensions should match like (3,2) @ (2,3) not (2,3) @ (2,3)

CPU times: user 1.79 ms, sys: 0 ns, total: 1.79 ms
Wall time: 10.1 ms


tensor(14)

In [16]:
#Transpose Multiplication
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])
torch.mm(tensor_A,tensor_B.T) #torch.mm is the same as torch.matmul (it's an alias for writing less code)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [17]:
#finding the min , max , mean, sum (tensor aggregation)
x = torch.arange(0,100,10)
torch.min(x), x.min()

(tensor(0), tensor(0))

In [18]:
x.max()

tensor(90)

In [19]:
# x.mean() #error --> wrong datatype
torch.mean(x.type(torch.float32))

tensor(45.)

In [20]:
x.argmin() #min value's position

tensor(0)

In [21]:
x.argmax() #max value's position

tensor(9)

In [22]:
#Reshapping, stacking, squeezing and unsqueezing , view, permute
x = torch.arange(1.,10.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [23]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [24]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [25]:
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked
#stack tensor

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [26]:
x_reshaped.squeeze() #remove all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [27]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [28]:
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,0,1)
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # the position of the shapes just changes

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [29]:
#Numpy array to tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [30]:
#tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [31]:
#Reproducbility
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6581, 0.6344, 0.6909, 0.6490],
        [0.1031, 0.9720, 0.1971, 0.2735],
        [0.3908, 0.4870, 0.5290, 0.0291]])
tensor([[0.1074, 0.8032, 0.1143, 0.1906],
        [0.4881, 0.7613, 0.7446, 0.6946],
        [0.2702, 0.6313, 0.5567, 0.8219]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [32]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [33]:
#running tensor and pytorch objects on GPUs
!nvidia-smi

Sun Jul 28 11:40:36 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [34]:
import torch
torch.cuda.is_available()

True

In [35]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [37]:
#create a tensor
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [38]:
# to bring back tensor from gpu to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])