<a href="https://colab.research.google.com/github/sush0677/pytorch_coding/blob/main/pytorchnotebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#pytorch fundamentals
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.3.1+cu121


In [3]:
#intro to tensors
scalar = torch.tensor(7)
scalar #lowercase naming

tensor(7)

In [5]:
scalar.ndim #dimension
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector #1 dimension #lowercase naming

tensor([7, 7])

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX #2 dimensions #uppercase

tensor([[ 7,  8],
        [ 9, 10]])

In [3]:
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR #it dimension is {1,3,3} #uppercase

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [5]:
#random tensor
random_tensor = torch.rand(3,4)
random_img_size_tensor = torch.rand(size=(224,224,3))
random_img_size_tensor.shape, random_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [7]:
#zeros and ones tensor
zeros = torch.zeros(size=(3,4))  # tensor datatype = torch.float
ones = torch.ones(size=(3,4))
zeros, ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [10]:
#creating a range of tensor
range= torch.arange(start=0,end=1000,step=77)
range

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [11]:
#creating tensors like
ten_zeros = torch.zeros_like(input=range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
float32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,
                              device=None,
                              requires_grad=False)
float32_tensor.dtype

torch.float32

In [14]:
# Manipulating tensors
tensor = torch.tensor([1,2,3])
tensor + 10
tensor * 10
tensor - 1

tensor([0, 1, 2])

In [15]:
torch.mul(tensor,10) #pytorch in built function(element-wise multiplication)

tensor([10, 20, 30])

In [18]:
#Matrix multiplication
%%time
torch.matmul(tensor,tensor) # matrix mul  symbol is @ The matrix inner dimensions should match like (3,2) @ (2,3) not (2,3) @ (2,3)

CPU times: user 104 µs, sys: 0 ns, total: 104 µs
Wall time: 108 µs


tensor(14)

In [19]:
#Transpose Multiplication
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])
torch.mm(tensor_A,tensor_B.T) #torch.mm is the same as torch.matmul (it's an alias for writing less code)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [20]:
#finding the min , max , mean, sum (tensor aggregation)
x = torch.arange(0,100,10)
torch.min(x), x.min()

(tensor(0), tensor(0))

In [21]:
x.max()

tensor(90)

In [24]:
# x.mean() #error --> wrong datatype
torch.mean(x.type(torch.float32))

tensor(45.)

In [25]:
x.argmin() #min value's position

tensor(0)

In [26]:
x.argmax() #max value's position

tensor(9)

In [27]:
#Reshapping, stacking, squeezing and unsqueezing , view, permute
x = torch.arange(1.,10.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [28]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [29]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [33]:
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked
#stack tensor

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])